import { ToastContainer } from 'react-toastify';
import ReduxProvider from '@/store/provider.js';
import '@/styles/globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang={'en'}>
      <body>
        <ToastContainer />
        <ReduxProvider> {children}</ReduxProvider>
      </body>
    </html>
  );
}
